version: '2'
services:
  redis:
    build: ./redis
    ports:
      - "6379:6379"
  nodered:
    build: ./node-red
    privileged: true
    ports:
      - "8080:8080"
  web:
    build: ./web
    ports:
      - "80:80"